/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as BattleOfTheFansRouteImport } from './routes/battle-of-the-fans'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BattleOfTheFansIndexRouteImport } from './routes/battle-of-the-fans.index'
import { Route as BattleOfTheFansPremierLeagueRouteImport } from './routes/battle-of-the-fans.premier-league'
import { Route as BattleOfTheFansHarambeeStarsRouteImport } from './routes/battle-of-the-fans.harambee-stars'
import { Route as BattleOfTheFansAboutRouteImport } from './routes/battle-of-the-fans.about'
import { Route as BattleOfTheFansArticlesSlugRouteImport } from './routes/battle-of-the-fans.articles.$slug'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleOfTheFansRoute = BattleOfTheFansRouteImport.update({
  id: '/battle-of-the-fans',
  path: '/battle-of-the-fans',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleOfTheFansIndexRoute = BattleOfTheFansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BattleOfTheFansRoute,
} as any)
const BattleOfTheFansPremierLeagueRoute =
  BattleOfTheFansPremierLeagueRouteImport.update({
    id: '/premier-league',
    path: '/premier-league',
    getParentRoute: () => BattleOfTheFansRoute,
  } as any)
const BattleOfTheFansHarambeeStarsRoute =
  BattleOfTheFansHarambeeStarsRouteImport.update({
    id: '/harambee-stars',
    path: '/harambee-stars',
    getParentRoute: () => BattleOfTheFansRoute,
  } as any)
const BattleOfTheFansAboutRoute = BattleOfTheFansAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => BattleOfTheFansRoute,
} as any)
const BattleOfTheFansArticlesSlugRoute =
  BattleOfTheFansArticlesSlugRouteImport.update({
    id: '/articles/$slug',
    path: '/articles/$slug',
    getParentRoute: () => BattleOfTheFansRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/battle-of-the-fans': typeof BattleOfTheFansRouteWithChildren
  '/brands': typeof BrandsRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/battle-of-the-fans/about': typeof BattleOfTheFansAboutRoute
  '/battle-of-the-fans/harambee-stars': typeof BattleOfTheFansHarambeeStarsRoute
  '/battle-of-the-fans/premier-league': typeof BattleOfTheFansPremierLeagueRoute
  '/battle-of-the-fans/': typeof BattleOfTheFansIndexRoute
  '/battle-of-the-fans/articles/$slug': typeof BattleOfTheFansArticlesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brands': typeof BrandsRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/battle-of-the-fans/about': typeof BattleOfTheFansAboutRoute
  '/battle-of-the-fans/harambee-stars': typeof BattleOfTheFansHarambeeStarsRoute
  '/battle-of-the-fans/premier-league': typeof BattleOfTheFansPremierLeagueRoute
  '/battle-of-the-fans': typeof BattleOfTheFansIndexRoute
  '/battle-of-the-fans/articles/$slug': typeof BattleOfTheFansArticlesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/battle-of-the-fans': typeof BattleOfTheFansRouteWithChildren
  '/brands': typeof BrandsRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/battle-of-the-fans/about': typeof BattleOfTheFansAboutRoute
  '/battle-of-the-fans/harambee-stars': typeof BattleOfTheFansHarambeeStarsRoute
  '/battle-of-the-fans/premier-league': typeof BattleOfTheFansPremierLeagueRoute
  '/battle-of-the-fans/': typeof BattleOfTheFansIndexRoute
  '/battle-of-the-fans/articles/$slug': typeof BattleOfTheFansArticlesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/battle-of-the-fans'
    | '/brands'
    | '/contact'
    | '/services'
    | '/battle-of-the-fans/about'
    | '/battle-of-the-fans/harambee-stars'
    | '/battle-of-the-fans/premier-league'
    | '/battle-of-the-fans/'
    | '/battle-of-the-fans/articles/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/brands'
    | '/contact'
    | '/services'
    | '/battle-of-the-fans/about'
    | '/battle-of-the-fans/harambee-stars'
    | '/battle-of-the-fans/premier-league'
    | '/battle-of-the-fans'
    | '/battle-of-the-fans/articles/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/battle-of-the-fans'
    | '/brands'
    | '/contact'
    | '/services'
    | '/battle-of-the-fans/about'
    | '/battle-of-the-fans/harambee-stars'
    | '/battle-of-the-fans/premier-league'
    | '/battle-of-the-fans/'
    | '/battle-of-the-fans/articles/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BattleOfTheFansRoute: typeof BattleOfTheFansRouteWithChildren
  BrandsRoute: typeof BrandsRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle-of-the-fans': {
      id: '/battle-of-the-fans'
      path: '/battle-of-the-fans'
      fullPath: '/battle-of-the-fans'
      preLoaderRoute: typeof BattleOfTheFansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle-of-the-fans/': {
      id: '/battle-of-the-fans/'
      path: '/'
      fullPath: '/battle-of-the-fans/'
      preLoaderRoute: typeof BattleOfTheFansIndexRouteImport
      parentRoute: typeof BattleOfTheFansRoute
    }
    '/battle-of-the-fans/premier-league': {
      id: '/battle-of-the-fans/premier-league'
      path: '/premier-league'
      fullPath: '/battle-of-the-fans/premier-league'
      preLoaderRoute: typeof BattleOfTheFansPremierLeagueRouteImport
      parentRoute: typeof BattleOfTheFansRoute
    }
    '/battle-of-the-fans/harambee-stars': {
      id: '/battle-of-the-fans/harambee-stars'
      path: '/harambee-stars'
      fullPath: '/battle-of-the-fans/harambee-stars'
      preLoaderRoute: typeof BattleOfTheFansHarambeeStarsRouteImport
      parentRoute: typeof BattleOfTheFansRoute
    }
    '/battle-of-the-fans/about': {
      id: '/battle-of-the-fans/about'
      path: '/about'
      fullPath: '/battle-of-the-fans/about'
      preLoaderRoute: typeof BattleOfTheFansAboutRouteImport
      parentRoute: typeof BattleOfTheFansRoute
    }
    '/battle-of-the-fans/articles/$slug': {
      id: '/battle-of-the-fans/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/battle-of-the-fans/articles/$slug'
      preLoaderRoute: typeof BattleOfTheFansArticlesSlugRouteImport
      parentRoute: typeof BattleOfTheFansRoute
    }
  }
}

interface BattleOfTheFansRouteChildren {
  BattleOfTheFansAboutRoute: typeof BattleOfTheFansAboutRoute
  BattleOfTheFansHarambeeStarsRoute: typeof BattleOfTheFansHarambeeStarsRoute
  BattleOfTheFansPremierLeagueRoute: typeof BattleOfTheFansPremierLeagueRoute
  BattleOfTheFansIndexRoute: typeof BattleOfTheFansIndexRoute
  BattleOfTheFansArticlesSlugRoute: typeof BattleOfTheFansArticlesSlugRoute
}

const BattleOfTheFansRouteChildren: BattleOfTheFansRouteChildren = {
  BattleOfTheFansAboutRoute: BattleOfTheFansAboutRoute,
  BattleOfTheFansHarambeeStarsRoute: BattleOfTheFansHarambeeStarsRoute,
  BattleOfTheFansPremierLeagueRoute: BattleOfTheFansPremierLeagueRoute,
  BattleOfTheFansIndexRoute: BattleOfTheFansIndexRoute,
  BattleOfTheFansArticlesSlugRoute: BattleOfTheFansArticlesSlugRoute,
}

const BattleOfTheFansRouteWithChildren = BattleOfTheFansRoute._addFileChildren(
  BattleOfTheFansRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BattleOfTheFansRoute: BattleOfTheFansRouteWithChildren,
  BrandsRoute: BrandsRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
